export var movieColors = {
  "Bottle Rocket": {
    Budget: "#F23030",
    BoxOff: "#F2CB57",
    StrokeFilled: "#0487D9",
    StrokeEmpty: "lightgray",
    Timeline: "#2C4001",
  },
  Rushmore: {
    Budget: "#11C5D9",
    BoxOff: "#FFD145", //"#F2C641",
    StrokeFilled: "#B02624",
    StrokeEmpty: "lightgray",
    Timeline: "#2484BF",
  },
  "The Royal Tenenbaums": {
    Budget: "lightsalmon",
    BoxOff: "lightseagreen",
    StrokeFilled: "#D90B0B",
    StrokeEmpty: "#F2DFBB",
    Timeline: "#7F4667",
  },
  "The Life Aquatic with Steve Zissou": {
    Budget: "#038C8C",
    BoxOff: "#F2CB05",
    StrokeFilled: "#004949",
    StrokeEmpty: "lightgray",
    Timeline: "#D23C35",
  },
  "The Darjeeling Limited": {
    Budget: "lightsalmon",
    BoxOff: "lightseagreen",
    StrokeFilled: "black",
    StrokeEmpty: "lightgray",
    Timeline: "#7F4667",
  },
  "Fantastic Mr. Fox": {
    Budget: "lightsalmon",
    BoxOff: "lightseagreen",
    StrokeFilled: "black",
    StrokeEmpty: "lightgray",
    Timeline: "#7F4667",
  },
  "Moonrise Kingdom": {
    StrokeFilled: "#261201", //"#BF2E21",
    Budget: "#D973A2", //"#7F4667", //"#73436B",
    BoxOff: "#EDD1D0", //"#D98FB1",
    StrokeEmpty: "#F2E8B3",
    Timeline: "#7F4667",
  },
  "The Grand Budapest Hotel": {
    StrokeFilled: "#D94929", //"#BF2E21",
    Budget: "#D973A2", //"#7F4667", //"#73436B",
    BoxOff: "#EDD1D0", //"#D98FB1",
    StrokeEmpty: "#F2E8B3",
    Timeline: "#7F4667",
  },
  "Isle of Dogs": {
    Budget: "lightsalmon",
    BoxOff: "lightseagreen",
    StrokeFilled: "black",
    StrokeEmpty: "lightgray",
    Timeline: "#7F4667",
  },
  "The French Dispatch": {
    Budget: "lightsalmon",
    BoxOff: "lightseagreen",
    StrokeFilled: "black",
    StrokeEmpty: "lightgray",
    Timeline: "#7F4667",
  },
};
